### ISSUE TITLE
Periodic resync thread can run before self.transport is set

### ISSUE THREAD

**Issue by fasaxc** [Metaswitch/calico#647]
We spawn the periodic resync thread before we set the transport.  That should be fine because we don't yield the greenlet.  Except, we log, which does IO, which yields the greenlet.

Basing this on this log:
```
2015-06-10 14:54:43.600 10226 INFO calico.openstack.mech_calico [-] Periodic resync thread started
2015-06-10 14:54:43.601 10226 ERROR calico.openstack.mech_calico [-] Periodic resync thread died!
2015-06-10 14:54:43.601 10226 TRACE calico.openstack.mech_calico Traceback (most recent call last):
2015-06-10 14:54:43.601 10226 TRACE calico.openstack.mech_calico   File "/usr/lib/python2.7/dist-packages/calico/openstack/mech_calico.py", line 556, in periodic_resync_thread
2015-06-10 14:54:43.601 10226 TRACE calico.openstack.mech_calico     if self.transport.is_master:
2015-06-10 14:54:43.601 10226 TRACE calico.openstack.mech_calico AttributeError: 'NoneType' object has no attribute 'is_master'
2015-06-10 14:54:43.601 10226 TRACE calico.openstack.mech_calico 
```
I don't think neutron died as a result, which could be a problem.

**Comment by fasaxc** [comment]
@Lukasa this touches the initialisation, which I think you're already working on for the DB-init stuff.

**Comment by fasaxc** [comment]
Oh, maybe this was a result of the deadlock caused by #641, which I was testing at the time.  Still, the logging could let this slip through, I think.

**Comment by fasaxc** [comment]
Given I was testing bad code, I'm inclined to punt this.

**Comment by eepyaich** [comment]
@Lukasa, @fasaxc - do we think this is actually an issue, or was it invalid testing?

**Comment by fasaxc** [comment]
@eepyaich I think it could still happen if writing to the log happens to block the greenlet.  It'd be hard to hit, though.

**Comment by Lukasa** [comment]
Agreed, but I think we should just fix it. =) I'm leaving it for now, but I may bring it into 0.26 if I make good progress on those issues.

**Comment by Lukasa** [comment]
Pulling into 0.26 because we're making excellent progress on this release.
